"""empty message

Revision ID: 55ba767b1592
Revises: 62182ebcba65
Create Date: 2016-04-12 02:58:01.381878

"""

# revision identifiers, used by Alembic.
revision = '55ba767b1592'
down_revision = '62182ebcba65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('myprofile', sa.Column('name', sa.String(length=80), nullable=True))
    op.add_column('myprofile', sa.Column('password', sa.String(), nullable=True))
    op.add_column('myprofile', sa.Column('url', sa.String(), nullable=True))
    op.create_index(op.f('ix_myprofile_email'), 'myprofile', ['email'], unique=True)
    op.drop_column('myprofile', 'first_name')
    op.drop_column('myprofile', 'last_name')
    op.drop_column('myprofile', 'high_score')
    op.drop_column('myprofile', 'image')
    op.drop_column('myprofile', 'sex')
    op.drop_column('myprofile', 'tdollars')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('tdollars', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('sex', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('image', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('high_score', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_myprofile_email'), table_name='myprofile')
    op.drop_column('myprofile', 'url')
    op.drop_column('myprofile', 'password')
    op.drop_column('myprofile', 'name')
    op.drop_column('myprofile', 'email')
    ### end Alembic commands ###
