"""empty message

Revision ID: 62182ebcba65
Revises: 04d8cb5c94e5
Create Date: 2016-03-06 21:34:11.214104

"""

# revision identifiers, used by Alembic.
revision = '62182ebcba65'
down_revision = '04d8cb5c94e5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('high_score', sa.String(length=80), nullable=True))
    op.add_column('myprofile', sa.Column('tdollars', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myprofile', 'tdollars')
    op.drop_column('myprofile', 'high_score')
    ### end Alembic commands ###
