"""empty message

Revision ID: 7944ee5e4bcc
Revises: 55ba767b1592
Create Date: 2016-04-12 03:32:31.294423

"""

# revision identifiers, used by Alembic.
revision = '7944ee5e4bcc'
down_revision = '55ba767b1592'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
