"""empty message

Revision ID: 7a2af0029f80
Revises: 7944ee5e4bcc
Create Date: 2016-04-12 03:32:39.635395

"""

# revision identifiers, used by Alembic.
revision = '7a2af0029f80'
down_revision = '7944ee5e4bcc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
